### ISSUE TITLE
Have a problem with gitlab structure

### ISSUE THREAD

**Issue by ZloyShadow** [lowitea/gitlobster#154]
Hello, when I'm trying to fetch all information via gitlab URL, I have a next problem

```
Error: error decoding response body: missing field `forks_count` at line 1 column 297834

Caused by:
    missing field `forks_count` at line 1 column 297834
```

How I can fix that, or I should use special flag?

**Comment by lowitea** [comment]
Hello!
Sorry for the long reply. There are some incomparable changes in the latest version of GitLab. I'm going to fix it this week.

**Comment by lowitea** [comment]
@ZloyShadow, please have a look at version 1.4.0
