### ISSUE TITLE
Pagination error

### ISSUE THREAD

**Issue by Alan-Shan** [lowitea/gitlobster#180]
When trying to clone large projects, Gitlobster fails with 
```
Error: HTTP status client error (405 Method Not Allowed) for url (https://domain.local/api/v4/projects?per_page=1000&page=51)
```
The JSON response for that request is as follows: 
```JSON
{"error":"Offset pagination has a maximum allowed offset of 50000 for requests that return objects of type Project. Remaining records can be retrieved using keyset pagination."}
```

Seems like we need to use keyset pagination. Is there an option to do so with this tool?

**Comment by lowitea** [comment]
It looks like you're right. In the near future (most likely on the weekend) I will move queries to keyset-based pagination

**Comment by lowitea** [comment]
@Alan-Shan Please try version 1.4.1  
Unfortunately, I myself cannot check on such a large number of projects. But I hope everything will work out :)

**Comment by Alan-Shan** [comment]
> @Alan-Shan Please try version 1.4.1 Unfortunately, I myself cannot check on such a large number of projects. But I hope everything will work out :)

Huge thanks for the quick reply! I'll try it out as soon as possible and get back to you with(hopefully positive) feedback. :)

**Comment by Alan-Shan** [comment]
@lowitea now it fails with 
````
./gitlobster --ft="token" --fu="url" --bt="token" --bu="url" --include="group" --verbose
2023-11-25T18:48:32.488780Z  WARN gitlobster::git: git exit status not success
2023-11-25T18:48:36.630467Z  WARN gitlobster::git: git exit status not success
Error: git error: fatal: not in a git directory
```
But I suppose that's unrelated since dry run works and I see the repos in /tmp/gitlobster. Also, strangely, all of them are valid git repositories.

**Comment by lowitea** [comment]
Thanks for the feedback. This is really strange, now I'll try to understand what's the matter

**Comment by lowitea** [comment]
What is your operating system and git version?

**Comment by lowitea** [comment]
And please run with `-vvvv` option

**Comment by lowitea** [comment]
I found a bug... Wait, I will create a new version

**Comment by lowitea** [comment]
The problem appeared in version 1.4.0. Please try version 1.4.2.

**Comment by Alan-Shan** [comment]
Yup, works like a charm. Thanks a lot!

Also, I've noticed the cloned repository remains in the /tmp/gitlobster folder. Is there a way to clone them repository after repository? The project I'm clonning is quite huge (around 1TB) and having to store one more full copy in the /tmp during the clone process might require a larger filesystem. I can manage that, but if there's an option that would be absolutely awesome. I tried looking into the codebase myself but Rust really isn't one of my strong sides, lol. Thanks for your help again!

**Comment by Alan-Shan** [comment]
I'm not sure what's going up with auth as well. I have a full access (sudo) token.
It's saved in the git config.

If I do `git clone http://domain.local/group/project.git`, everything works.
However `git clone http://username:token@domain.local/group/project.git` it doesn't. Really strange behaviour. I can always just clone by SSH, I suppose, but just wanted to point out if anyone stumbles upon the same issue. Not a problem with gitlobster though it seems.

**Comment by lowitea** [comment]
@Alan-Shan Hi! I'm really glad it worked out! :)

> Is there a way to clone them repository after repository?

Unfortunately not at the moment. An important feature of gitlobster is the incremental update of repositories after the first full download. You need to have a local copy for this. But I will make a issue to make it possible.

> If I do git clone http://domain.local/group/project.git, everything works. However git clone http://username:token@domain.local/group/project.git doesn't. Really strange behaviour.

Yeah, it's really strange. I'm testing gitlobster with the public version of gitlab and it works there. I have a test token with permissions: api, read_repository (and write_repository for uploading). I'll try to test on private repositories, maybe it's some gitlab settings. Thanks a lot for your feedback! :)

**Comment by Alan-Shan** [comment]
@lowitea 
> Unfortunately not at the moment. An important feature of gitlobster is the incremental update of repositories after the first full download. You need to have a local copy for this. But I will make a issue to make it possible.
The `--dst` can be used to store that copy in another folder rather than /tmp, correct?

**Comment by lowitea** [comment]
> The `--dst` can be used to store that copy in another folder rather than /tmp, correct?

Yes, that's right (or short version `-d`)

**Comment by Alan-Shan** [comment]
@lowitea 
Hey.

Is there a way to retain the group name? Right now all groups are named by their path rather than name. 

That's usually not so big of an issue with the repositories named using latin characters in the first place. However replacing the name with path doesn't really help if the original repo name was cyrillic for example or arabic.

**Comment by lowitea** [comment]
@Alan-Shan 
Yes, it is, I'll see what's with it in the near future

And I will close this issue as done.
I opened another issue about the names of groups #184.
