### ISSUE TITLE
Add the ability to push repositories to the GitLab root

### ISSUE THREAD

**Issue by lowitea** [lowitea/gitlobster#36]
https://github.com/lowitea/gitlobster/issues/33#issuecomment-1381928645

**Comment by Macleykun** [comment]
Workaround currently:
Create a temporary group (make sure the name is not the same of the name of the top group will be) on the destination.
Specify the group name: `--bg=groupname`
Once the sync finished, you want to visit your group by going into: Burger icon > Groups > View all groups.
Click on the 3 dots and hit edit.
Expand the advanced tab.
Under: Transfer group choose in the menu of Select parent group choose: no parent group.
Verify the group is in the right place.
Repeat this for every group, in the end remove the temporarly group for import.

Again, i appricate your help alot!
