### ISSUE TITLE
Projectslug is used as name, instead of actual name of repo

### ISSUE THREAD

**Issue by Macleykun** [lowitea/gitlobster#54]
First of all, thank you again for making this program! It really made migrating easy and painless!
I did check all of our repo's side by side. And noticed only one being different from what i've seen from our old environment.

![example](https://user-images.githubusercontent.com/26381427/218050703-6e41cd5c-c807-4461-b43c-79a999a93295.png)

The above is an example i made as i deleted the one in the old environment.

It seems that when someone changes the Project slug to something else then what is proposed when creating a project. That later when migrating the Project name inherits it from the Project slug.

![image](https://user-images.githubusercontent.com/26381427/218051295-07114d93-652e-4147-ab49-e6d700f032be.png)

**Comment by lowitea** [comment]
Hi! :)
This is true... I know about it but I thought that since slug is used for the name of the local folder, then it should also be used in the destination repository. Now this solution doesn't seem good to me anymore.
I'll fix it soon)

**Comment by Macleykun** [comment]
Thanks! And no need to rush things :) <3
